/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.frames;

import controle.gui.ControleFPreferencias;
import controle.gui.ControleFrameBackup;

/**
 *
 * @author maycon
 */
public class frameBackup extends javax.swing.JFrame {

    private ControleFrameBackup controle = new ControleFrameBackup(this);
    
    /**
     * Creates new form frameBackup
     */
    public frameBackup() {
        initComponents();
        
        controle.inicializa();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIcone = new javax.swing.JLabel();
        labelAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema Brittos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setEnabled(false);
        setForeground(java.awt.Color.white);
        setResizable(false);

        labelIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panels/Backup.png"))); // NOI18N

        labelAviso.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        labelAviso.setText("Realizando Backup...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAviso, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelIcone, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
            .addComponent(labelAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAviso;
    private javax.swing.JLabel labelIcone;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getLabelAviso() {
        return labelAviso;
    }

    public void setLabelAviso(javax.swing.JLabel labelAviso) {
        this.labelAviso = labelAviso;
    }

    public javax.swing.JLabel getLabelIcone() {
        return labelIcone;
    }

    public void setLabelIcone(javax.swing.JLabel labelIcone) {
        this.labelIcone = labelIcone;
    }

       
    

}
