package br.com.areiasbrittos.controle.objetos;
// Generated 01/03/2012 13:32:49 by Hibernate Tools 3.2.1.GA

/**
 * CaixadiarioHasContasreceber generated by hbm2java
 */
public class CaixadiarioHasContasreceber implements java.io.Serializable, java.lang.Comparable {

    private int idCaixaDiarioHasContasReceber;
    private Caixadiario caixadiario;
    private Contasreceber contasreceber;

    public CaixadiarioHasContasreceber() {
    }

    public CaixadiarioHasContasreceber(Caixadiario caixadiario, Contasreceber contasreceber) {
        this.caixadiario = caixadiario;
        this.contasreceber = contasreceber;
    }

    public CaixadiarioHasContasreceber(int idCaixaDiarioHasContasReceber, Caixadiario caixadiario, Contasreceber contasreceber) {
        this.idCaixaDiarioHasContasReceber = idCaixaDiarioHasContasReceber;
        this.caixadiario = caixadiario;
        this.contasreceber = contasreceber;
    }

    public int getIdCaixaDiarioHasContasReceber() {
        return this.idCaixaDiarioHasContasReceber;
    }

    public void setIdCaixaDiarioHasContasReceber(int idCaixaDiarioHasContasReceber) {
        this.idCaixaDiarioHasContasReceber = idCaixaDiarioHasContasReceber;
    }

    public Caixadiario getCaixadiario() {
        return this.caixadiario;
    }

    public void setCaixadiario(Caixadiario caixadiario) {
        this.caixadiario = caixadiario;
    }

    public Contasreceber getContasreceber() {
        return this.contasreceber;
    }

    public void setContasreceber(Contasreceber contasreceber) {
        this.contasreceber = contasreceber;
    }

    @Override
    public int compareTo(Object o) {

        CaixadiarioHasContasreceber obj = (CaixadiarioHasContasreceber) o;

        if (this.getContasreceber().getHoraPagamento().before(obj.getContasreceber().getHoraPagamento())) {
            return -1;
        } else if(this.getContasreceber().getHoraPagamento().equals(obj.getContasreceber().getHoraPagamento())){
            return 0;
        }else {
            return 1;
        }
    }
    
    @Override
    public boolean equals(Object o){
        
        CaixadiarioHasContasreceber obj = (CaixadiarioHasContasreceber) o;
        
        if(this.idCaixaDiarioHasContasReceber == obj.idCaixaDiarioHasContasReceber){
            return true;
        }
        if(this.caixadiario.getIdCaixaDiario() == obj.caixadiario.getIdCaixaDiario() 
                && this.contasreceber.getIdConta() == this.contasreceber.getIdConta()){
            return true;
        } else {
            return false;
        }
    }
    
    @Override
    public int hashCode() {
        int hash = 3;
        hash = 17 * hash + this.idCaixaDiarioHasContasReceber;
        hash = 17 * hash + (this.caixadiario != null ? this.caixadiario.getIdCaixaDiario() : 0);
        hash = 17 * hash + (this.contasreceber != null ? this.contasreceber.getIdConta() : 0);
        return hash;
    }
}
