package br.com.areiasbrittos.controle.objetos;
// Generated 01/03/2012 13:32:49 by Hibernate Tools 3.2.1.GA

/**
 * CaixadiarioHasContaspagar generated by hbm2java
 */
public class CaixadiarioHasContaspagar implements java.io.Serializable, java.lang.Comparable {

    private int idCaixaDiarioHasContasPagar;
    private Caixadiario caixadiario;
    private Contaspagar contaspagar;

    public CaixadiarioHasContaspagar() {
    }

    public CaixadiarioHasContaspagar(Caixadiario caixadiario, Contaspagar contaspagar) {
        this.caixadiario = caixadiario;
        this.contaspagar = contaspagar;
    }

    public CaixadiarioHasContaspagar(int idCaixaDiarioHasContasPagar, Caixadiario caixadiario, Contaspagar contaspagar) {
        this.idCaixaDiarioHasContasPagar = idCaixaDiarioHasContasPagar;
        this.caixadiario = caixadiario;
        this.contaspagar = contaspagar;
    }

    public int getIdCaixaDiarioHasContasPagar() {
        return this.idCaixaDiarioHasContasPagar;
    }

    public void setIdCaixaDiarioHasContasPagar(int idCaixaDiarioHasContasPagar) {
        this.idCaixaDiarioHasContasPagar = idCaixaDiarioHasContasPagar;
    }

    public Caixadiario getCaixadiario() {
        return this.caixadiario;
    }

    public void setCaixadiario(Caixadiario caixadiario) {
        this.caixadiario = caixadiario;
    }

    public Contaspagar getContaspagar() {
        return this.contaspagar;
    }

    public void setContaspagar(Contaspagar contaspagar) {
        this.contaspagar = contaspagar;
    }

    @Override
    public int compareTo(Object o) {
        
        CaixadiarioHasContaspagar obj = (CaixadiarioHasContaspagar) o;
        
        if(this.getContaspagar().getHoraPagamento().before(obj.getContaspagar().getHoraPagamento())){
            return -1;
        } else {
            return 1;
        }
    }
    
    @Override
    public boolean equals(Object o){
        
        CaixadiarioHasContaspagar obj = (CaixadiarioHasContaspagar) o;
        
        if(this.idCaixaDiarioHasContasPagar == obj.idCaixaDiarioHasContasPagar){
            return true;
        }
        
        if(this.caixadiario.getIdCaixaDiario() == obj.caixadiario.getIdCaixaDiario() 
                && this.contaspagar.getIdConta() == this.contaspagar.getIdConta()){
            return true;
        } else {
            return false;
        }
        
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 17 * hash + this.idCaixaDiarioHasContasPagar;
        hash = 17 * hash + (this.caixadiario != null ? this.caixadiario.getIdCaixaDiario() : 0);
        hash = 17 * hash + (this.contaspagar != null ? this.contaspagar.getIdConta() : 0);
        return hash;
    }
}
