package br.com.areiasbrittos.controle.objetos;
// Generated 01/03/2012 13:32:49 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.util.HashSet;
import java.util.Set;

/**
 * Contasreceber generated by hbm2java
 */
public class Contasreceber implements java.io.Serializable, java.lang.Comparable {

    private Integer idConta;
    private Pesagem pesagem;
    private Venda venda;
    private String descricao;
    private String observacao;
    private Date dataVencimento;
    private Date dataPagamento;
    private Time horaPagamento;
    private BigDecimal valor;
    private boolean quitada;
    private Set caixadiarioHasContasrecebers = new HashSet(0);

    public Contasreceber() {
    }
    
    public Contasreceber(String descricao, Date dataVencimento, Date dataPagamento, Time horaPagamento, BigDecimal valor, boolean quitada) {
        this.descricao = descricao;
        this.dataVencimento = dataVencimento;
        this.dataPagamento = dataPagamento;
        this.horaPagamento = horaPagamento;
        this.valor = valor;
        this.quitada = quitada;
    }

    public Contasreceber(Pesagem pesagem, Venda venda, String descricao, String observacao, Date dataVencimento, Date dataPagamento, Time horaPagamento, BigDecimal valor, boolean quitada) {
        this.pesagem = pesagem;
        this.venda = venda;
        this.descricao = descricao;
        this.observacao = observacao;
        this.dataVencimento = dataVencimento;
        this.dataPagamento = dataPagamento;
        this.horaPagamento = horaPagamento;
        this.valor = valor;
        this.quitada = quitada;
    }
    public Contasreceber(Integer idConta, Pesagem pesagem, Venda venda, String descricao, String observacao, Date dataVencimento, Date dataPagamento, Time horaPagamento, BigDecimal valor, boolean quitada) {
        this(pesagem, venda, descricao, observacao, dataVencimento, dataPagamento, horaPagamento, valor, quitada);
        this.idConta = idConta;
    }
    public Contasreceber(Pesagem pesagem, Venda venda, String descricao, String observacao, Date dataVencimento, Date dataPagamento, Time horaPagamento, BigDecimal valor, boolean quitada, Set caixadiarioHasContasrecebers) {
        this.pesagem = pesagem;
        this.venda = venda;
        this.descricao = descricao;
        this.observacao = observacao;
        this.dataVencimento = dataVencimento;
        this.dataPagamento = dataPagamento;
        this.horaPagamento = horaPagamento;
        this.valor = valor;
        this.quitada = quitada;
        this.caixadiarioHasContasrecebers = caixadiarioHasContasrecebers;
    }

    @Override
    public String toString() {
        return "Contasreceber{" + "idConta=" + idConta + ", pesagem=" + pesagem + ", venda=" + venda + ", descricao=" + descricao + ", observacao=" + observacao + ", dataVencimento=" + dataVencimento + ", dataPagamento=" + dataPagamento + ", horaPagamento=" + horaPagamento + ", valor=" + valor + ", quitada=" + quitada + ", caixadiarioHasContasrecebers=" + caixadiarioHasContasrecebers + '}';
    }
    
    public Integer getIdConta() {
        return this.idConta;
    }

    public void setIdConta(Integer idConta) {
        this.idConta = idConta;
    }

    public Pesagem getPesagem() {
        return this.pesagem;
    }

    public void setPesagem(Pesagem pesagem) {
        this.pesagem = pesagem;
    }

    public Venda getVenda() {
        return this.venda;
    }

    public void setVenda(Venda venda) {
        this.venda = venda;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getObservacao() {
        return this.observacao;
    }

    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    public Date getDataVencimento() {
        return this.dataVencimento;
    }

    public void setDataVencimento(Date dataVencimento) {
        this.dataVencimento = dataVencimento;
    }

    public Date getDataPagamento() {
        return this.dataPagamento;
    }

    public void setDataPagamento(Date dataPagamento) {
        this.dataPagamento = dataPagamento;
    }

    public Time getHoraPagamento() {
        return this.horaPagamento;
    }

    public void setHoraPagamento(Time horaPagamento) {
        this.horaPagamento = horaPagamento;
    }

    public BigDecimal getValor() {
        return this.valor;
    }

    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    public boolean isQuitada() {
        return this.quitada;
    }

    public void setQuitada(boolean quitada) {
        this.quitada = quitada;
    }

    public Set getCaixadiarioHasContasrecebers() {
        return this.caixadiarioHasContasrecebers;
    }

    public void setCaixadiarioHasContasrecebers(Set caixadiarioHasContasrecebers) {
        this.caixadiarioHasContasrecebers = caixadiarioHasContasrecebers;
    }

    @Override
    public int compareTo(Object o) {
        return this.compareTo(o);
    }
    
    //compara por hora
    public int compareTo(Contasreceber outraConta) {

        if (this.getHoraPagamento().before(outraConta.getHoraPagamento())) {
            return -1;
        } else {
            return 1;
        }
    }

    
}
