package br.com.areiasbrittos.controle.objetos;
// Generated 28/02/2011 20:01:11 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 * Entidade generated by hbm2java
 */
public class Entidade  implements java.io.Serializable {


     private Integer idEntidade;
     private String nome;
     private String fantasia;
     private String cidade;
     private String estado;
     private String logradouro;
     private String numero;
     private String bairro;
     private String cep;
     private String cpfCnpj;
     private String telefone;
     private String celular;
     private String fax;
     private String inscricaoEstadual;
     private String tipo;
     private boolean pesJuridica;
     private Set pesagems = new HashSet(0);
     private Set compras = new HashSet(0);
     private Set vendas = new HashSet(0);

    public Entidade() {
    }

	
    public Entidade(String nome, String tipo, boolean pesJuridica) {
        this.nome = nome;
        this.tipo = tipo;
        this.pesJuridica = pesJuridica;
    }
    public Entidade(String nome, String fantasia, String cidade, String estado, 
            String logradouro, String numero, String bairro, String cep,
            String cpfCnpj, String telefone, String celular,
            String fax, String inscricaoEstadual, String tipo,
            boolean pesJuridica, Set pesagems) {
       this.nome = nome;
       this.fantasia = fantasia;
       this.cidade = cidade;
       this.estado = estado;
       this.logradouro = logradouro;
       this.numero = numero;
       this.bairro = bairro;
       this.cep = cep;
       this.cpfCnpj = cpfCnpj;
       this.telefone = telefone;
       this.celular = celular;
       this.fax = fax;
       this.inscricaoEstadual = inscricaoEstadual;
       this.tipo = tipo;
       this.pesJuridica = pesJuridica;
       this.pesagems = pesagems;
    }

        public Entidade(String nome, String fantasia, String cidade, String estado,
            String logradouro, String numero, String bairro, String cep, String
            cpfCnpj, String telefone, String celular, String fax,
            String inscricaoEstadual, String tipo, boolean pesJuridica) {
        this(nome, tipo, pesJuridica);

       this.fantasia = fantasia;
       this.cidade = cidade;
       this.estado = estado;
       this.logradouro = logradouro;
       this.numero = numero;
       this.bairro = bairro;
       this.cep = cep;
       this.cpfCnpj = cpfCnpj;
       this.telefone = telefone;
       this.celular = celular;
       this.fax = fax;
       this.inscricaoEstadual = inscricaoEstadual;

    }
   
    public Integer getIdEntidade() {
        return this.idEntidade;
    }
    
    public void setIdEntidade(Integer idEntidade) {
        this.idEntidade = idEntidade;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getFantasia() {
        return this.fantasia;
    }
    
    public void setFantasia(String fantasia) {
        this.fantasia = fantasia;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getCpfCnpj() {
        return this.cpfCnpj;
    }
    
    public void setCpfCnpj(String cpfCnpj) {
        this.cpfCnpj = cpfCnpj;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getInscricaoEstadual() {
        return this.inscricaoEstadual;
    }
    
    public void setInscricaoEstadual(String inscricaoEstadual) {
        this.inscricaoEstadual = inscricaoEstadual;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public boolean isPesJuridica() {
        return this.pesJuridica;
    }
    
    public void setPesJuridica(boolean pesJuridica) {
        this.pesJuridica = pesJuridica;
    }
    public Set getPesagems() {
        return this.pesagems;
    }
    
    public void setPesagems(Set pesagems) {
        this.pesagems = pesagems;
    }

    public Set getCompras() {
        return compras;
    }

    public Set getVendas() {
        return vendas;
    }
    
    public void setCompras(Set compras){
        this.compras = compras;
    }
    
    public void setVendas(Set vendas){
        this.vendas = vendas;
    }

}


