package br.com.areiasbrittos.controle.objetos;
// Generated 28/02/2011 20:01:11 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;

/**
 * Pesagem generated by hbm2java
 */
public class Pesagem implements java.io.Serializable {

    private Integer idPesagem;
    private Entidade entidade;
    private Date dataCriacao;
    private Time horaCriacao;
    private Date dataAlteracao;
    private Time horaAlteracao;
    private int pesoBruto;
    private int tara;
    private int pesoLiquido;
    private String placa;
    private BigDecimal valorPesagem;
    private Date vencimento;
    private boolean quitada;
    private String motorista;
    private String pagamento;
    private boolean concluida;

    public Pesagem() {
    }

    public Pesagem(Entidade entidade, Date dataCriacao, Time horaCriacao, Date dataAlteracao, Time horaAlteracao, int pesoBruto,
            int tara, int pesoLiquido, String placa, BigDecimal valorPesagem,
            Date vencimento, boolean quitada, String pagamento, boolean concluida) {
        this.entidade = entidade;
        this.dataCriacao = dataCriacao;
        this.horaCriacao = horaCriacao;
        this.dataAlteracao = dataAlteracao;
        this.horaAlteracao = horaAlteracao;
        this.pesoBruto = pesoBruto;
        this.tara = tara;
        this.pesoLiquido = pesoLiquido;
        this.placa = placa;
        this.valorPesagem = valorPesagem;
        this.vencimento = vencimento;
        this.quitada = quitada;
        this.pagamento = pagamento;
        this.concluida = concluida;
    }

    public Pesagem(Entidade entidade, Date dataCriacao, Time horaCriacao, Date dataAlteracao, Time horaAlteracao, int pesoBruto,
            int tara, int pesoLiquido, String placa, BigDecimal valorPesagem,
            Date vencimento, boolean quitada, String motorista, String pagamento, boolean concluida) {
        this.entidade = entidade;
        this.dataCriacao = dataCriacao;
        this.horaCriacao = horaCriacao;
        this.dataAlteracao = dataAlteracao;
        this.horaAlteracao = horaAlteracao;
        this.pesoBruto = pesoBruto;
        this.tara = tara;
        this.pesoLiquido = pesoLiquido;
        this.placa = placa;
        this.valorPesagem = valorPesagem;
        this.vencimento = vencimento;
        this.quitada = quitada;
        this.motorista = motorista;
        this.pagamento = pagamento;
        this.concluida = concluida;
    }

    public Integer getIdPesagem() {
        return this.idPesagem;
    }

    public void setIdPesagem(Integer idPesagem) {
        this.idPesagem = idPesagem;
    }

    public Entidade getEntidade() {
        return this.entidade;
    }

    public void setEntidade(Entidade entidade) {
        this.entidade = entidade;
    }

    public int getPesoBruto() {
        return this.pesoBruto;
    }

    public void setPesoBruto(int pesoBruto) {
        this.pesoBruto = pesoBruto;
    }

    public int getTara() {
        return this.tara;
    }

    public void setTara(int tara) {
        this.tara = tara;
    }

    public int getPesoLiquido() {
        return this.pesoLiquido;
    }

    public void setPesoLiquido(int pesoLiquido) {
        this.pesoLiquido = pesoLiquido;
    }

    public String getPlaca() {
        return this.placa;
    }

    public void setPlaca(String placa) {
        this.placa = placa;
    }

    public BigDecimal getValorPesagem() {
        return this.valorPesagem;
    }

    public void setValorPesagem(BigDecimal valorPesagem) {
        this.valorPesagem = valorPesagem;
    }

    public Date getVencimento() {
        return this.vencimento;
    }

    public void setVencimento(Date vencimento) {
        this.vencimento = vencimento;
    }

    public boolean isQuitada() {
        return this.quitada;
    }

    public void setQuitada(boolean quitada) {
        this.quitada = quitada;
    }

    public String getMotorista() {
        return this.motorista;
    }

    public void setMotorista(String motorista) {
        this.motorista = motorista;
    }

    public boolean isConcluida() {
        return concluida;
    }

    public void setConcluida(boolean ativa) {
        this.concluida = ativa;
    }

    public Date getDataCriacao() {
        return dataCriacao;
    }

    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }

    public Time getHoraCriacao() {
        return horaCriacao;
    }

    public void setHoraCriacao(Time horaCriacao) {
        this.horaCriacao = horaCriacao;
    }

    public Date getDataAlteracao() {
        return dataAlteracao;
    }

    public void setDataAlteracao(Date dataAlteracao) {
        this.dataAlteracao = dataAlteracao;
    }

    public Time getHoraAlteracao() {
        return horaAlteracao;
    }

    public void setHoraAlteracao(Time horaAlteracao) {
        this.horaAlteracao = horaAlteracao;
    }

    public String getPagamento() {
        return pagamento;
    }

    public void setPagamento(String pagamento) {
        this.pagamento = pagamento;
    }
}
