package br.com.areiasbrittos.controle.objetos;
// Generated 11/01/2012 10:46:41 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Integer idProduto;
     private String nome;
     private int estoque;
     private BigDecimal precoAVista;
     private BigDecimal precoAPrazo;
     private boolean ativo;
     private Set vendaHasProdutos = new HashSet(0);
     private Set compraHasProdutos = new HashSet(0);

    public Produto() {
    }

	
    public Produto(String nome, int estoque, BigDecimal precoAVista, BigDecimal precoAPrazo, boolean ativo) {
        this.nome = nome;
        this.estoque = estoque;
        this.precoAVista = precoAVista;
        this.precoAPrazo = precoAPrazo;
        this.ativo = ativo;
    }
    public Produto(String nome, int estoque, BigDecimal precoAVista, BigDecimal precoAPrazo, boolean ativo, Set vendaHasProdutos, Set compraHasProdutos) {
       this.nome = nome;
       this.estoque = estoque;
       this.precoAVista = precoAVista;
        this.precoAPrazo = precoAPrazo;
       this.ativo = ativo;
       this.vendaHasProdutos = vendaHasProdutos;
       this.compraHasProdutos = compraHasProdutos;
    }
   
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public int getEstoque() {
        return this.estoque;
    }
    
    public void setEstoque(int estoque) {
        this.estoque = estoque;
    }
    public BigDecimal getPrecoAVista() {
        return this.precoAVista;
    }
    
    public void setPrecoAVista(BigDecimal precoAVista) {
        this.precoAVista = precoAVista;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public Set getVendaHasProdutos() {
        return this.vendaHasProdutos;
    }
    
    public void setVendaHasProdutos(Set vendaHasProdutos) {
        this.vendaHasProdutos = vendaHasProdutos;
    }
    public Set getCompraHasProdutos() {
        return this.compraHasProdutos;
    }
    
    public void setCompraHasProdutos(Set compraHasProdutos) {
        this.compraHasProdutos = compraHasProdutos;
    }

    public BigDecimal getPrecoAPrazo() {
        return precoAPrazo;
    }

    public void setPrecoAPrazo(BigDecimal precoAPrazo) {
        this.precoAPrazo = precoAPrazo;
    }

    


}


