package br.com.areiasbrittos.controle.objetos;
// Generated 06/09/2011 03:19:15 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Tabelapesagem generated by hbm2java
 */
public class Tabelapesagem  implements java.io.Serializable {

     private Integer idTabelaPesagem;
     private int tara;
     private String nome;
     private BigDecimal precoAVista;
     private BigDecimal precoAPrazo;

    public Tabelapesagem() {
    }

    public Tabelapesagem(int tara, String nome, BigDecimal precoAVista, BigDecimal precoAPrazo) {
       this.tara = tara;
       this.nome = nome;
       this.precoAVista = precoAVista;
       this.precoAPrazo = precoAPrazo;
    }
   
    public Integer getIdTabelaPesagem() {
        return this.idTabelaPesagem;
    }
    
    public void setIdTabelaPesagem(Integer idTabelaPesagem) {
        this.idTabelaPesagem = idTabelaPesagem;
    }
    public int getTara() {
        return this.tara;
    }
    
    public void setTara(int tara) {
        this.tara = tara;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public BigDecimal getPrecoAVista() {
        return precoAVista;
    }

    public void setPrecoAVista(BigDecimal precoAVista) {
        this.precoAVista = precoAVista;
    }

    public BigDecimal getPrecoAPrazo() {
        return precoAPrazo;
    }

    public void setPrecoAPrazo(BigDecimal precoAPrazo) {
        this.precoAPrazo = precoAPrazo;
    }





}


