package br.com.areiasbrittos.controle.objetos.seguranca;
// Generated 06/09/2011 03:48:18 by Hibernate Tools 3.2.1.GA



/**
 * PermissaoUsuario generated by hbm2java
 */
public class PermissaoUsuario  implements java.io.Serializable {


     private PermissaoUsuarioId id;
     private Usuario usuario;
     private Permissao idPermissao;
     private boolean permissao;

    public PermissaoUsuario() {
    }

    public PermissaoUsuario(PermissaoUsuarioId id, Usuario usuario, Permissao idPermissao, boolean permissao) {
       this(usuario, idPermissao, permissao);
       this.id = id;
    }
    
    public PermissaoUsuario(Usuario usuario, Permissao idPermissao, boolean acesso){
        this.setUsuario(usuario);
        this.setIdPermissao(idPermissao);
        this.setPermissao(acesso);
        this.setId(new PermissaoUsuarioId(idPermissao.getIdPermissao(), usuario.getIdUsuario()));
    }
   
    public PermissaoUsuarioId getId() {
        return this.id;
    }
    
    public void setId(PermissaoUsuarioId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Permissao getIdPermissao() {
        return this.idPermissao;
    }
    
    public void setIdPermissao(Permissao permissao) {
        this.idPermissao = permissao;
    }
    public boolean isPermissao() {
        return this.permissao;
    }
    
    public void setPermissao(boolean permissao_1) {
        this.permissao = permissao_1;
    }




}


