package br.com.areiasbrittos.controle.objetos.seguranca;
// Generated 06/09/2011 03:48:18 by Hibernate Tools 3.2.1.GA



/**
 * PermissaoUsuarioId generated by hbm2java
 */
public class PermissaoUsuarioId  implements java.io.Serializable {


     private int idPermissao;
     private int idUsuario;

    public PermissaoUsuarioId() {
    }

    public PermissaoUsuarioId(int idPermissao, int idUsuario) {
       this.idPermissao = idPermissao;
       this.idUsuario = idUsuario;
    }
   
    public int getIdPermissao() {
        return this.idPermissao;
    }
    
    public void setIdPermissao(int idPermissao) {
        this.idPermissao = idPermissao;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PermissaoUsuarioId) ) return false;
		 PermissaoUsuarioId castOther = ( PermissaoUsuarioId ) other; 
         
		 return (this.getIdPermissao()==castOther.getIdPermissao())
 && (this.getIdUsuario()==castOther.getIdUsuario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPermissao();
         result = 37 * result + this.getIdUsuario();
         return result;
   }   


}


