package br.com.areiasbrittos.controle.objetos.seguranca;
// Generated 06/09/2011 02:52:35 by Hibernate Tools 3.2.1.GA


import java.sql.Date;
import java.sql.Time;

/**
 * Transacao generated by hbm2java
 */
public class Transacao  implements java.io.Serializable {


     private Integer idTransacao;
     private Usuario usuario;
     private Date data;
     private Time hora;
     private String transacao;

    public Transacao() {
    }

    public Transacao(Usuario usuario, Date data, Time hora, String transacao) {
       this.usuario = usuario;
       this.data = data;
       this.hora = hora;
       this.transacao = transacao;
    }
    public Transacao(Usuario usuario, String transacao){
        this.setData();
        this.setHora();
        this.usuario = usuario;
        this.transacao = transacao;
    }
   
    public Integer getIdTransacao() {
        return this.idTransacao;
    }
    
    public void setIdTransacao(Integer idTransacao) {
        this.idTransacao = idTransacao;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(){
        this.data = new Date(System.currentTimeMillis());
    }
    public void setData(Date data) {
        this.data = data;
    }
    public Time getHora() {
        return this.hora;
    }

    public void setHora(){
        this.hora = new Time(System.currentTimeMillis());
    }    
    public void setHora(Time hora) {
        this.hora = hora;
    }
    public String getTransacao() {
        return this.transacao;
    }
    
    public void setTransacao(String transacao) {
        this.transacao = transacao;
    }




}


