package br.com.areiasbrittos.controle.objetos.seguranca;
// Generated 05/09/2011 13:06:37 by Hibernate Tools 3.2.1.GA


import java.sql.Date;
import java.util.HashSet;
import java.util.Set;
import br.com.areiasbrittos.controle.utils.Criptografia;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String login;
     private String senha;
     private String nome;
     private boolean ativo;
     private Date validade;
     private Set permissaoUsuarios = new HashSet(0);
     private Set transacaos = new HashSet(0);

    public Usuario() {
    }
    
    public Usuario(String login, String nome, boolean ativo, Date validade) {
        this.setLogin(login);
        this.setNome(nome);
        this.setAtivo(ativo);
        this.setValidade(validade);
        this.setSenhaComMD5("123");
    }
	
    public Usuario(String login, String senha, String nome, boolean ativo, Date validade) {
        this(login, nome, ativo, validade);
        this.setSenhaComMD5(senha);
    }
    public Usuario(String login, String senha, String nome, boolean ativo, Date validade, Set permissaoUsuarios, Set transacaos) {
       this(login, senha, nome, ativo, validade);
       this.setPermissaoUsuarios(permissaoUsuarios);
       this.setTransacaos(transacaos);
    }
    public Usuario(int IdUsuario){
        this.idUsuario = idUsuario;
    }
    
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenhaComMD5(String senha) {
        this.senha = Criptografia.md5(senha);
    }
    public void setSenha(String senha){
        this.senha = senha;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public Date getValidade() {
        return this.validade;
    }
    
    public void setValidade(Date validade) {
        this.validade = validade;
    }
    public Set getPermissaoUsuarios() {
        return this.permissaoUsuarios;
    }
    
    public void setPermissaoUsuarios(Set permissaoUsuarios) {
        this.permissaoUsuarios = permissaoUsuarios;
    }
    public Set getTransacaos() {
        return this.transacaos;
    }
    
    public void setTransacaos(Set transacaos) {
        this.transacaos = transacaos;
    }




}


